services:
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile.frontend
      context: ./
    restart: always
    ports:
      - "127.0.0.1:5173:80"
    healthcheck:
      test: [ "CMD", "curl", "-X", "POST", "http://localhost:5173/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - faucet
      - devnet

  devnet:
    container_name: devnet
    build:
      dockerfile: Dockerfile.devnet
      context: ./
    restart: always
    ports:
      - "127.0.0.1:9650:9650"
    volumes:
      - devnet_go_mod:/go/pkg/mod
      - devnet_go_build:/root/.cache/go-build
    healthcheck:
      test: [ "CMD", "curl", "-X", "POST", "http://localhost:9650/ext/bc/hypervm/coreapi", "-H", "Content-Type: application/json", "-d", "{\"jsonrpc\":\"2.0\",\"method\":\"hypersdk.network\",\"params\":{},\"id\":1}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 300s

  faucet:
    container_name: faucet
    build:
      dockerfile: Dockerfile.faucet
      context: ./
    environment:
      - FAUCET_PRIVATE_KEY_HEX=323b1d8f4eed5f0da9da93071b034f2dce9d2d22692c172f3cb252a64ddfafd01b057de320297c29ad0c1f589ea216869cf1938d88c9fbd70d6748323dbf2fa7
      - RPC_ENDPOINT=http://devnet:9650
    restart: always
    ports:
      - "127.0.0.1:8765:8765"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8765/readyz" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      devnet:
        condition: service_healthy

volumes:
  devnet_go_mod:
  devnet_go_build:


