# Build stage
FROM node:22-bookworm AS build
WORKDIR /app
COPY web_wallet/package.json web_wallet/package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm install
COPY web_wallet/ ./web_wallet/
WORKDIR /app/web_wallet
RUN npm run build-no-check 

# # Production stage
FROM nginx:latest
COPY --from=build /app/web_wallet/dist /usr/share/nginx/html
