#####
# Build the keygen
#####

FROM golang:1.22-bookworm AS keygen-builder

WORKDIR /build
COPY ./go.mod ./go.sum ./

COPY ./vm ./vm

ENV GOMODCACHE=/go/pkg/mod
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -o build/keygen ./vm/cmd/keygen

#####
# Final layer with keygen, VM and avalanchego
#####
FROM debian:bookworm-slim

COPY --from=keygen-builder /build/build/keygen /keygen

ENTRYPOINT ["/keygen"]
