# Build stage
FROM node:22-bookworm AS build

WORKDIR /app

COPY web_wallet/package.json web_wallet/package-lock.json ./

RUN npm ci --cache .npm --prefer-offline

COPY web_wallet/ ./

RUN npm run build

# Production stage
FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
