FROM node:20-bookworm AS builder
    
WORKDIR /app/web_wallet
COPY web_wallet/package*.json ./
RUN npm ci

COPY web_wallet /app/web_wallet

# RUN CI=yes npm run test
RUN npm run build

FROM nginx:1.27

COPY --from=builder /app/web_wallet/dist /usr/share/nginx/html